# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: |
    echo Downloading Polaris CLI
    curl -L https://uat01.dev.polaris.synopsys.com/api/tools/polaris_cli-win64.zip --output %TMP%\polaris.zip
    powershell.exe -NoP -NonI -Command "Expand-Archive '%TMP%\polaris.zip' '%TMP%\polaris'"
    dir %TMP%
    dir %TMP%\polaris
    echo Running polaris setup
    echo SourceBranchName is %Build.SourceBranchName%
    echo SourceBranch is %Build.SourceBranch%
    git branch
    %TMP%\polaris\polaris_cli-win64-1.5.5193\bin\polaris configure